// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpeiOWISOAh0AvkKNwBPnoD2YNfqGYFU',
    appId: '1:106281026987:web:dd591c6a05534d6c4bbeee',
    messagingSenderId: '106281026987',
    projectId: 'asr-notes-app',
    authDomain: 'asr-notes-app.firebaseapp.com',
    storageBucket: 'asr-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2h4WeTpCCuPCiIZjsym5rJ1UcewEZmI',
    appId: '1:106281026987:android:c01fe74b7108f1ed4bbeee',
    messagingSenderId: '106281026987',
    projectId: 'asr-notes-app',
    storageBucket: 'asr-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLi-IntK1F6WLl81BOzOe8kDYrOgJ3APs',
    appId: '1:106281026987:ios:f98f84e9f433172a4bbeee',
    messagingSenderId: '106281026987',
    projectId: 'asr-notes-app',
    storageBucket: 'asr-notes-app.appspot.com',
    iosClientId: '106281026987-ukhog2vc88kd77kafq775alauumgkvqa.apps.googleusercontent.com',
    iosBundleId: 'com.asr.notesapp.notesTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLi-IntK1F6WLl81BOzOe8kDYrOgJ3APs',
    appId: '1:106281026987:ios:45881bd15d43053e4bbeee',
    messagingSenderId: '106281026987',
    projectId: 'asr-notes-app',
    storageBucket: 'asr-notes-app.appspot.com',
    iosClientId: '106281026987-9tv3jjp1amd4h49gf9s7o1nnpvl0b89u.apps.googleusercontent.com',
    iosBundleId: 'com.asr.notesapp.notesTakingApp.RunnerTests',
  );
}
